version: '3.8'
services:
  devcontainer:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ~/.ssh:/home/vscode/.ssh:ro
      - ~/.aws:/home/vscode/.aws:ro
    network_mode: service:db
    command: sleep infinity

  db:
    image: postgres:12
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres

volumes:
  postgres-data: